/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f2',
        'surface-dim': '#dcdad3',
        'surface-bright': '#fcf9f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ec',
        'surface-container': '#f0eee7',
        'surface-container-high': '#ebe8e1',
        'surface-container-highest': '#e5e2db',
        'surface-variant': '#e5e2db',
        'surface-tint': '#546527',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#45483c',
        'outline': '#76786a',
        'outline-variant': '#c6c8b8',
        'primary': '#516225',
        'primary-container': '#6a7b3b',
        'on-primary': '#ffffff',
        'on-primary-container': '#fbffe5',
        'primary-fixed': '#d6eb9f',
        'primary-fixed-dim': '#bbcf85',
        'on-primary-fixed': '#151f00',
        'on-primary-fixed-variant': '#3d4c11',
        'secondary': '#556523',
        'secondary-container': '#d7eb9a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5b6b28',
        'secondary-fixed': '#d7eb9a',
        'secondary-fixed-dim': '#bccf81',
        'on-secondary-fixed': '#161e00',
        'on-secondary-fixed-variant': '#3d4c0c',
        'tertiary': '#6f5748',
        'tertiary-container': '#8a6f60',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#fedcc9',
        'tertiary-fixed-dim': '#e0c0ae',
        'on-tertiary-fixed': '#29180c',
        'on-tertiary-fixed-variant': '#584234',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#fcf9f2',
        'on-background': '#1c1c18',
        'inverse-surface': '#31312c',
        'inverse-on-surface': '#f3f0e9',
        'inverse-primary': '#bbcf85',
        // Agro-Heritage specific foliage & semantic accents
        'harvest-olive': '#718342',
        'harvest-olive-dark': '#5d6d34',
        'sunlit-sage': '#91a35a',
        'sprout-wash': '#f0f4e8',
        'charred-soil': '#4a3528',
        'umber-brown': '#7d6552',
        'silt-gray': '#8a7768',
        'pressed-sand': '#e7ded0',
        'yield-green': '#587e3e',
        'mandi-gold': '#b87b31',
        'terracotta-red': '#9b4533',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'gutter-mobile': '1rem',
        'margin': '2.5rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        headline: ['Playfair Display', 'serif'],
        body: ['DM Sans', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        label: ['DM Sans', 'sans-serif'],
      },
      boxShadow: {
        'soft-umber': '0 2px 8px rgba(74, 53, 40, 0.04), 0 1px 2px rgba(74, 53, 40, 0.02)',
        'modal-tray': '0 12px 32px rgba(74, 53, 40, 0.08), 0 4px 8px rgba(74, 53, 40, 0.03)',
      },
    },
  },
  plugins: [],
};
